---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
  activity <- read.csv("D:/MYRWORKS/RepData_PeerAssessment1/RepData_PeerAssessment1/activity.csv", colClasses = c("numeric", "character", "numeric"))
  head(activity)
  names(activity)
  library(lattice)
  activity$date <- as.Date(activity$date, "%Y-%m-%d")

```


## What is mean total number of steps taken per day?

```{r}

  StepsTotal <- aggregate(steps ~ date, data = activity, sum, na.rm = TRUE)
  head(StepsTotal)

#Histogram  Display
  hist(StepsTotal$steps, main = "Total steps by day", xlab = "day", col = "yellow")

#Mean and median of the total number of steps taken per day
#Mean
  mean(StepsTotal$steps)

#Median
  median(StepsTotal$steps)


```

## What is the average daily activity pattern?
```{r}
#Time series plot 
  time_series <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)
#The plot 

plot(row.names(time_series), time_series, type = "l", xlab = "5-min interval", 
    ylab = "Average across all Days", main = "Average number of steps taken", 
    col = "red")

# 5-minute interval
max_interval <- which.max(time_series)
names(max_interval)


```



## Imputing missing values

```{r}
#Total number of missing values in the dataset 
activity_NA <- sum(is.na(activity))
activity_NA

#Devise a strategy for filling in all of the missing values in the dataset
StepsAverage <- aggregate(steps ~ interval, data = activity, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(activity)) {
    obs <- activity[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(StepsAverage, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    fillNA <- c(fillNA, steps)
}

#Create a new dataset that is equal to the original dataset 
new_activity <- activity
new_activity$steps <- fillNA

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day

StepsTotal2 <- aggregate(steps ~ date, data = new_activity, sum, na.rm = TRUE)

# Histogram is 
hist(StepsTotal2$steps, main = "Total steps by day", xlab = "day", col = "Green")

# And the mean and median is
mean(StepsTotal2$steps)

median(StepsTotal2$steps)

```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
# Create a new factor variable in the dataset with two levels - "weekday" and "weekend"

day <- weekdays(activity$date)
daylevel <- vector()
for (i in 1:nrow(activity)) {
    if (day[i] == "Saturday") {
        daylevel[i] <- "Weekend"
    } else if (day[i] == "Sunday") {
        daylevel[i] <- "Weekend"
    } else {
        daylevel[i] <- "Weekday"
    }
}
activity$daylevel <- daylevel
activity$daylevel <- factor(activity$daylevel)

stepsByDay <- aggregate(steps ~ interval + daylevel, data = activity, mean)
names(stepsByDay) <- c("interval", "daylevel", "steps")

#Make a panel plot containing a time series plot 
xyplot(steps ~ interval | daylevel, stepsByDay, type = "l", layout = c(1, 2), 
    xlab = "Interval", ylab = "Number of steps")


```

